WebQuanLySinhVienDonGian/Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebQuanLySinhVienDonGian.Models
{
    public class SinhVien
    {
        public int maSinhVien { get; set; }
        public string hoLot { get; set; }
        public string ten { get; set; }
        public string lop { get; set; }
        public bool nu { get; set; }
        public int khoa { get; set; }
        public DateTime ngaySinh { get; set; }
    }
}

WebQuanLySinhVienDonGian/Controllers/SinhVienController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using WebQuanLySinhVienDonGian.Models;
using System.Text.Json;
using System.Text;

namespace WebQuanLySinhVienDonGian.Controllers
{
    public class SinhVienController : Controller
    {
        string urlApi = "http://localhost:8080/";

        public async Task<IActionResult> Index()
        {
            List<SinhVien> sinhViens = new List<SinhVien>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(urlApi+"sinhvien"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    sinhViens = JsonSerializer.Deserialize<List<SinhVien>>(apiResponse);
                }
            }
            return View(sinhViens);
        }

        [HttpGet]
        public IActionResult ThemSinhVien()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ThemSinhVien(SinhVien sv)
        {
            string requestBody = JsonSerializer.Serialize(sv);
            HttpContent body = new StringContent(requestBody, Encoding.UTF8, "application/json");
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsync(urlApi + "sinhvien", body))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["ThongBao"] = "alert('Thêm thành công')";
                        return RedirectToAction("Index");
                    }
                }    
            }
            TempData["ThongBao"] = "alert('Thêm thất bại')";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CapNhatSinhVien(int id)
        {
            SinhVien sinhVien;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(urlApi + "sinhvien/detail?id="+id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    sinhVien = JsonSerializer.Deserialize<SinhVien>(apiResponse);
                }
            }
            return View(sinhVien);
        }

        [HttpPost]
        public async Task<IActionResult> CapNhatSinhVien(SinhVien sv)
        {
            string requestBody = JsonSerializer.Serialize(sv);
            HttpContent body = new StringContent(requestBody, Encoding.UTF8, "application/json");
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PutAsync(urlApi + "sinhvien", body))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["ThongBao"] = "alert('Cập nhật thành công')";
                        return RedirectToAction("Index");
                    }
                }
            }
            TempData["ThongBao"] = "alert('Cập nhật thất bại')";
            return View();
        }

        public async Task<IActionResult> XoaSinhVien(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync(urlApi + "sinhvien?id="+id))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["ThongBao"] = "alert('Xoá thành công')";
                    }
                    else
                    {
                        TempData["ThongBao"] = "alert('Xoá thất bại')";
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

WebQuanLySinhVienDonGian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

WebQuanLySinhVienDonGian/Views/SinhVien/CapNhatSinhVien.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model WebQuanLySinhVienDonGian.Models.SinhVien

@if (TempData["ThongBao"] != null)
{
    <script type="text/javascript">
            window.onload = function () {
                @Html.Raw(TempData["ThongBao"]);
            };
    </script>
}

<h1 class="text-center" style="margin:40px">Nhập thông tin sinh viên</h1>

<form asp-controller="SinhVien" asp-action="CapNhatSinhVien" method="post">
    <div class="form-group">
        <label>Mã sinh viên:</label>
        <input asp-for="@Model.maSinhVien" type="text" readonly class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.hoLot">Họ lót</label>
        <input asp-for="@Model.hoLot" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.ten">Tên</label>
        <input asp-for="@Model.ten" type="text" class="form-control">
    </div>
    <div class="form-check">
        <input asp-for="@Model.nu" type="checkbox" class="form-check-input">
        <label asp-for="@Model.nu" class="form-check-label">Nữ</label>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ngaySinh">Ngày sinh</label>
        <input asp-for="@Model.ngaySinh" type="date" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.khoa">Khoá</label>
        <input asp-for="@Model.khoa" type="number" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.lop">Lớp</label>
        <input asp-for="@Model.lop" type="text" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Cập nhật</button>
</form>

WebQuanLySinhVienDonGian/Views/SinhVien/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<WebQuanLySinhVienDonGian.Models.SinhVien>

@if (TempData["ThongBao"] != null)
{
    <script type="text/javascript">
            window.onload = function () {
                @Html.Raw(TempData["ThongBao"]);
            };
    </script>
}

<h1 class="text-center" style="margin:40px">Quản lý sinh viên</h1>
<a asp-controller="SinhVien" asp-action="ThemSinhVien" type="button" class="btn btn-primary" style="margin:20px 0px">Thêm sinh viên</a>
<table class="table table-striped">
    <thead>
        <tr class="table-info">
            <th scope="col">Mã sinh viên</th>
            <th scope="col">Họ lót</th>
            <th scope="col">Tên</th>
            <th scope="col">Giới tính</th>
            <th scope="col">Ngày sinh</th>
            <th scope="col">Khoá</th>
            <th scope="col">Lớp</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var sv in Model)
        {
        <tr>
            <td>@sv.maSinhVien</td>
            <td>@sv.hoLot</td>
            <td>@sv.ten</td>
            @if (sv.nu)
            {
                <td>Nữ</td>
            }
            else
            {
                <td>Nam</td>
            }
            <td>@String.Format("{0:dd/MM/yyyy}", sv.ngaySinh)</td>
            <td>@sv.khoa</td>
            <td>@sv.lop</td>
            <td>
                <a asp-controller="SinhVien" asp-action="CapNhatSinhVien" asp-route-id="@sv.maSinhVien" class="btn btn-danger">Cập nhật</a>
                <a asp-controller="SinhVien" asp-action="XoaSinhVien" asp-route-id="@sv.maSinhVien" class="btn btn-danger">Xoá</a>
            </td>
        </tr>
        }
    </tbody>
</table>

WebQuanLySinhVienDonGian/Views/SinhVien/ThemSinhVien.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model WebQuanLySinhVienDonGian.Models.SinhVien

@if (TempData["ThongBao"] != null)
{
    <script type="text/javascript">
            window.onload = function () {
                @Html.Raw(TempData["ThongBao"]);
            };
    </script>
}

<h1 class="text-center" style="margin:40px">Nhập thông tin sinh viên</h1>

<form asp-controller="SinhVien" asp-action="ThemSinhVien" method="post">
    <div class="form-group">
        <label asp-for="@Model.hoLot">Họ lót</label>
        <input asp-for="@Model.hoLot" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.ten">Tên</label>
        <input asp-for="@Model.ten" type="text" class="form-control">
    </div>
    <div class="form-check">
        <input asp-for="@Model.nu" type="checkbox" class="form-check-input">
        <label asp-for="@Model.nu" class="form-check-label">Nữ</label>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ngaySinh">Ngày sinh</label>
        <input asp-for="@Model.ngaySinh" type="date" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.khoa">Khoá</label>
        <input asp-for="@Model.khoa" type="number" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@Model.lop">Lớp</label>
        <input asp-for="@Model.lop" type="text" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Thêm</button>
</form>